# Generated by Django 4.2.2 on 2023-08-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_total_amount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='checkoutdetail_model',
            old_name='CheckoutDetail_zipcode',
            new_name='zipcode',
        ),
    ]
