# Generated by Django 4.2.2 on 2023-08-17 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_checkoutdetail_address_checkoutdetail_model_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 12, 10, 41, 295938, tzinfo=datetime.timezone.utc)),
        ),
    ]
