# Generated by Django 4.2.2 on 2023-08-19 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_checkoutdetail_model_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 19, 5, 21, 16, 752663, tzinfo=datetime.timezone.utc)),
        ),
    ]
