# Generated by Django 4.2.2 on 2023-08-23 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_checkoutdetail_model_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 23, 14, 37, 46, 728355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
