# Generated by Django 4.2.2 on 2023-08-25 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_alter_checkoutdetail_model_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 0, 3, 44, 986768, tzinfo=datetime.timezone.utc)),
        ),
    ]
