# Generated by Django 4.2.2 on 2023-08-29 19:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('checkout', '0028_alter_checkoutdetail_model_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetail_model',
            name='date_added',
        ),
        migrations.AddField(
            model_name='checkoutdetail_model',
            name='date_added_now',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 19, 51, 32, 123243, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ordermodel'),
        ),
        migrations.AlterField(
            model_name='checkoutdetail_model',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
