# Generated by Django 4.2.2 on 2023-08-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_delete_updateorder_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='tax_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.CharField(help_text='Enter Tax', max_length=30)),
                ('total_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tax_accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_tax', to='orders.productmodel')),
            ],
        ),
    ]
