# Generated by Django 4.2.2 on 2023-08-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax_model',
            old_name='tax_accountant',
            new_name='tax_product_name',
        ),
        migrations.RenameField(
            model_name='tax_model',
            old_name='total_amount',
            new_name='tax_tax',
        ),
    ]
