# Generated by Django 4.2.2 on 2023-08-25 13:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_delete_updateorder_model'),
        ('tax', '0002_rename_tax_accountant_tax_model_tax_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_model',
            name='price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='tax_model',
            name='tax_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tax_model',
            name='tax',
            field=models.CharField(help_text='Enter Tax', max_length=30, verbose_name='Tax %'),
        ),
        migrations.AlterField(
            model_name='tax_model',
            name='tax_product_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_tax', to='orders.productmodel'),
        ),
        migrations.AlterField(
            model_name='tax_model',
            name='tax_tax',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='tax_tax %'),
        ),
    ]
