# Generated by Django 4.2.2 on 2023-08-25 13:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_tax_model_price_tax_model_tax_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax_model',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=20, null=True, verbose_name='Tax %'),
        ),
        migrations.AlterField(
            model_name='tax_model',
            name='tax',
            field=models.CharField(help_text='Enter Tax', max_length=30, verbose_name='Tax1 %'),
        ),
        migrations.AlterField(
            model_name='tax_model',
            name='tax_tax',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='tax_tax2 %'),
        ),
    ]
