# Generated by Django 4.2.2 on 2023-08-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_alter_tax_model_price_alter_tax_model_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax_model',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='tax_model',
            name='tax_price',
        ),
        migrations.RemoveField(
            model_name='tax_model',
            name='tax_tax',
        ),
    ]
