# Generated by Django 4.2.2 on 2023-08-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_remove_tax_model_tax_remove_tax_model_tax_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax_model',
            old_name='price',
            new_name='tax',
        ),
        migrations.RemoveField(
            model_name='tax_model',
            name='tax_product_name',
        ),
    ]
