# Generated by Django 4.2.2 on 2023-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0007_alter_tax_model_options_alter_tax_model_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_model',
            name='divide_one_hundred',
            field=models.PositiveIntegerField(blank=True, default=15, null=True, verbose_name='100'),
        ),
    ]
