# Generated by Django 4.2.2 on 2023-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0008_tax_model_divide_one_hundred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax_model',
            name='divide_one_hundred',
            field=models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='100'),
        ),
    ]
