# Generated by Django 4.2.2 on 2023-08-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='confirmed_Order',
            new_name='shipment_track_confirmed_Order',
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='order_date',
            new_name='shipment_track_confirmed_Order_date',
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='delivered',
            new_name='shipment_track_delivered',
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='on_the_way',
            new_name='shipment_track_on_the_way',
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='order_id',
            new_name='shipment_track_order_id',
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='shipped',
            new_name='shipment_track_shipped',
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='order_user',
            new_name='shipment_track_user',
        ),
        migrations.RemoveField(
            model_name='shipmenttrackmodel',
            name='date_aq',
        ),
    ]
