# Generated by Django 4.2.2 on 2023-08-19 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_shipment', '0002_rename_confirmed_order_shipmenttrackmodel_shipment_track_confirmed_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmenttrackmodel',
            options={'ordering': ('-shipment_track_confirmed_Order_date',), 'verbose_name': 'Shipment Track', 'verbose_name_plural': 'Shipment Tracs'},
        ),
        migrations.AlterField(
            model_name='shipmenttrackmodel',
            name='shipment_track_confirmed_Order_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 19, 4, 18, 30, 294179, tzinfo=datetime.timezone.utc)),
        ),
    ]
