# Generated by Django 4.2.2 on 2023-08-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_shipment', '0003_alter_shipmenttrackmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmenttrackmodel',
            options={'ordering': ('-shipment_track_order_id',), 'verbose_name': 'Shipment Track', 'verbose_name_plural': 'Shipment Tracs'},
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='shipment_track_confirmed_Order',
            new_name='shipment_track_Processing_order',
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='shipment_track_delivered',
            new_name='shipment_track_Product_delivered',
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='shipment_track_on_the_way',
            new_name='shipment_track_confirmed_order',
        ),
        migrations.RenameField(
            model_name='shipmenttrackmodel',
            old_name='shipment_track_shipped',
            new_name='shipment_track_delivery',
        ),
        migrations.RemoveField(
            model_name='shipmenttrackmodel',
            name='shipment_track_confirmed_Order_date',
        ),
        migrations.AddField(
            model_name='shipmenttrackmodel',
            name='shipment_track_dispatch_product',
            field=models.BooleanField(default=False),
        ),
    ]
