# Generated by Django 4.2.2 on 2023-08-29 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('track_shipment', '0004_alter_shipmenttrackmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttrackmodel',
            name='shipment_track_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel'),
        ),
    ]
