# Generated by Django 4.2.2 on 2023-08-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetailsmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetailsmodel',
            options={'ordering': ('-OrderDetails_order',), 'verbose_name': 'Order Detail', 'verbose_name_plural': 'Order Details'},
        ),
    ]
