# Generated by Django 4.2.2 on 2023-08-17 22:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_updateorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateOrder_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime(2023, 8, 17, 22, 45, 6, 808829, tzinfo=datetime.timezone.utc))),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='UpdateOrder',
        ),
    ]
