# Generated by Django 4.2.2 on 2023-08-18 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_updateorder_model_delete_updateorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateorder_model',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 18, 21, 49, 21, 764717, tzinfo=datetime.timezone.utc)),
        ),
    ]
