# Generated by Django 4.2.2 on 2023-08-18 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_updateorder_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateorder_model',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 18, 22, 54, 23, 826445, tzinfo=datetime.timezone.utc)),
        ),
    ]
