# Generated by Django 4.2.2 on 2023-08-19 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_updateorder_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateorder_model',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 19, 4, 18, 30, 292614, tzinfo=datetime.timezone.utc)),
        ),
    ]
