# Generated by Django 4.2.2 on 2023-08-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_updateorder_model_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateOrder_MODEL',
        ),
    ]
